insert into roles (name) values ('admin');
insert into roles (name) values ('operator');
insert into roles (name) values ('user');
insert into rules (rule) values ('create item');
insert into rules (rule) values ('delete item');
insert into rules (rule) values ('read item');
insert into rules (rule) values ('update item');
insert into categories (name) values ('problem');
insert into categories (name) values ('setup');
insert into categories (name) values ('task');
insert into states (name) values ('new');
insert into states (name) values ('in work');
insert into states (name) values ('done');
insert into roles_rules (role_id, rule_id) values (1,1);
insert into roles_rules (role_id, rule_id) values (1,2);
insert into roles_rules (role_id, rule_id) values (1,3);
insert into roles_rules (role_id, rule_id) values (1,4);
insert into users (name, role_id) values ('admin', 1);
insert into items (header, users_id, category_id,state_id) values ('test', 1, 3, 1);
insert into comments (description, item_id) values ('test comment', 1);
insert into attachs (attach, item_id) values ('src/main/java/ru/job4j/sql/1_to_1.jpg', 1);
insert into attachs (attach, item_id) values ('src/main/java/ru/job4j/sql/1_to_many.jpg', 1);